### ISSUE TITLE
Unit conversion classes do not work if located outside labscript_utils.unit_conversions

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript#71]
The title says it all: Unit conversion classes do not work if located outside labscript_utils.unit_conversions

This should have been done for the v3.0.0 release. The import machinery exists in labscript_utils, and BLACS is updated to use it. But labscript was never updated to store the fully qualified import path. We should rectify this and release it in v3.0.1

**Comment by chrisjbillington** [comment]
Huh, I thought this was the first thing I did on this feature, and I spent enough time working on the other components that I would not have been able to test them at all if I had not. Maybe I did but I forgot to actually make a PR and the code never left my own computer.

Should be an easy fix, self-assigning.
